# Generated by Django 2.0.2 on 2019-12-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_auto_20191205_1309'),
        ('xsauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collect',
            field=models.ManyToManyField(related_name='collectors', related_query_name='collectors', to='novel.Novel'),
        ),
    ]
