# Generated by Django 2.0.2 on 2019-12-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsauth', '0003_user_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pen_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
