# Generated by Django 2.0.2 on 2019-12-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xsauth', '0004_user_pen_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
    ]
