# Generated by Django 2.0.2 on 2019-12-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_novel_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
