# Generated by Django 2.0.2 on 2019-12-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_auto_20191204_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novelchapter',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='novel',
            name='is_recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='novel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
