# Generated by Django 2.0.2 on 2019-12-05 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_auto_20191204_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to=settings.AUTH_USER_MODEL),
        ),
    ]
