# Generated by Django 2.0.2 on 2019-12-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_auto_20191207_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('hint', models.CharField(max_length=200)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
