# Generated by Django 2.0.2 on 2019-12-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.IntegerField(null=True),
        ),
    ]
