# Generated by Django 2.0.2 on 2019-12-07 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0010_advertisement_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
