# Generated by Django 2.0.2 on 2019-12-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0011_auto_20191207_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='link_to',
            field=models.URLField(null=True),
        ),
    ]
