# Generated by Django 2.0.2 on 2019-12-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0012_advertisement_link_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='link_to',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
