# Generated by Django 2.0.2 on 2019-12-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0015_auto_20191207_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.NovelTag'),
        ),
    ]
