# Generated by Django 2.0.2 on 2019-12-08 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0016_novel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='tag',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='novel.NovelTag'),
            preserve_default=False,
        ),
    ]
