# Generated by Django 2.0.2 on 2019-12-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0017_auto_20191208_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novels', related_query_name='novels', to='novel.NovelCategory'),
        ),
        migrations.AlterField(
            model_name='novelchapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', related_query_name='chapters', to='novel.Novel'),
        ),
    ]
