# Generated by Django 2.0.2 on 2019-12-09 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0018_auto_20191209_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', related_query_name='novels', to=settings.AUTH_USER_MODEL),
        ),
    ]
