# Generated by Django 2.0.2 on 2019-12-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0019_auto_20191209_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcellentWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link_to', models.URLField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.IntegerField()),
            ],
        ),
    ]
