# Generated by Django 2.0.2 on 2019-12-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0020_excellentworks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ['-pub_date'], 'permissions': (('recommend_novel', 'can recommend novel'),)},
        ),
    ]
